name: Creates clever cloud app with database

on: 
  workflow_dispatch:
    inputs:
      app_name:
        description: Application name
        required: true
      db_name:
        description: Database name
        required: true
        
jobs:

  create_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download cli
        run: git fetch --prune --unshallow
      - run: curl -O https://clever-tools.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz
      - run: tar xvzf clever-tools-latest_linux.tar.gz
      - run: ./clever-tools-latest_linux/clever login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
      - run: ./clever-tools-latest_linux/clever create --type docker ${{github.event.inputs.app_name}}
      - run: ./clever-tools-latest_linux/clever addon create postgresql-addon ${{github.event.inputs.db_name}} --link ${{github.event.inputs.app_name}}
      - run: ./clever-tools-latest_linux/clever env set SPRING_PROFILES_ACTIVE "clever_cloud"
          
          
    
